spring:
  datasource:
    username: ${DB_USERNAME:admin}
    url: jdbc:postgresql://${DB_URL:localhost:15432/userservicedb?charSet=UTF-8}
    password: ${DB_PASSWORD:admin}
    tomcat:
      connection-properties: useUnicode=true;characterEncoding=utf8
    sql-script-encoding: 'UTF-8'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'false'
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: 'false'
  http:
    encoding:
      charset: 'UTF-8'
      force: true

  cache:
    jcache:
      provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
    cache-names:
      - getUser
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s

server:
  port: 8084