spring:
  datasource:
    username: ${DB_USERNAME:admin}
    url: jdbc:postgresql://${DB_URL:localhost:15432/userservicedb?charSet=UTF-8}
    password: ${DB_PASSWORD:admin}
    tomcat:
      connection-properties: useUnicode=true;characterEncoding=utf8
    sql-script-encoding: 'UTF-8'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'false'
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: 'false'
  http:
    encoding:
      charset: 'UTF-8'
      force: true

  cache:
    jcache:
      provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
    cache-names:
      - getUser
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s

security:
  api-header-name: "X-API-KEY"
  api-key: ${API_KEY:key}
  jwt-secret: ${JWT_SECRET:5b8d21e3c97e73d229cb581e963697a3cb62def55327da16b374f28079cb223c}
  jwt-expiration-ms: ${JWT_EXPIRATION:3600000}
  jwt-refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION:604800000}
  cors-url: ${CORS_URL:http://localhost:3000}